#!/usr/bin/env bash
# build-display-font.sh — regenerate the bundled display face in style.css (W11).
#
# The PMOS substrate base64-inlines ONE subset weight of JetBrains Mono (700) as
# the display face (headings, wordmark, section counters), so every emitted
# artifact is self-contained: no server, no internet, no CDN (which would leak
# the viewer's IP and add an external render dependency). Code/pre stay on the
# system mono stack — only the display role uses the bundled face.
#
# This script is the documented, reproducible source of the base64 blob embedded
# in ../style.css between the `@font-face` sentinels. It is NOT run at artifact
# emit time — it is a maintenance tool. Re-run it only to change the bundled
# face, weight, or glyph coverage.
#
# Requires: curl, python3 with fontTools + brotli (pip install --user fonttools brotli).
#
# Usage:
#   bash build-display-font.sh            # regenerate and rewrite ../style.css in place
#   bash build-display-font.sh --print    # print the @font-face block to stdout only
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
STYLE_CSS="$HERE/../style.css"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# 1. Fetch the upstream Latin-subset weight (OFL; freely redistributable).
SRC_URL="https://cdn.jsdelivr.net/fontsource/fonts/jetbrains-mono@latest/latin-700-normal.woff2"
curl -sS -m 30 -o "$TMP/jbm-700.woff2" "$SRC_URL"

# 2. Subset to the glyphs PMOS docs actually use (ASCII + common doc punctuation).
#    Headings can contain any Latin letter/digit/punctuation, so keep all of basic
#    Latin plus the smart-punctuation / symbol set the substrate emits.
python3 -m fontTools.subset "$TMP/jbm-700.woff2" \
  --unicodes="U+0020-007E,U+00A0,U+00A7,U+00B7,U+2013,U+2014,U+2018,U+2019,U+201C,U+201D,U+2026,U+2192" \
  --layout-features='' --no-hinting --desubroutinize \
  --flavor=woff2 --output-file="$TMP/jbm-700-subset.woff2"

# 3. Emit the @font-face block (base64-inlined).
B64="$(base64 < "$TMP/jbm-700-subset.woff2" | tr -d '\n')"
BLOCK_FILE="$TMP/fontface.css"
{
  echo '/* @font-face:start — generated by assets/fonts/build-display-font.sh; do not hand-edit the base64 */'
  echo '@font-face {'
  echo '  font-family: "JetBrains Mono";'
  echo '  font-style: normal;'
  echo '  font-weight: 700;'
  echo '  font-display: swap;'
  printf '  src: url(data:font/woff2;base64,%s) format("woff2");\n' "$B64"
  echo '}'
  echo '/* @font-face:end */'
} > "$BLOCK_FILE"

if [ "${1:-}" = "--print" ]; then
  cat "$BLOCK_FILE"
  exit 0
fi

# 4. Replace the existing block (between the sentinels) in style.css, or fail loudly.
if ! grep -q '/\* @font-face:start' "$STYLE_CSS"; then
  echo "ERROR: no '@font-face:start' sentinel in $STYLE_CSS — add the block once by hand, then re-run." >&2
  exit 1
fi
python3 - "$STYLE_CSS" "$BLOCK_FILE" <<'PY'
import re, sys
style_path, block_path = sys.argv[1], sys.argv[2]
css = open(style_path, encoding="utf-8").read()
block = open(block_path, encoding="utf-8").read().rstrip("\n")
new = re.sub(r"/\* @font-face:start.*?/\* @font-face:end \*/", block, css, count=1, flags=re.S)
open(style_path, "w", encoding="utf-8").write(new)
print(f"rewrote @font-face block in {style_path} ({len(block)} bytes)")
PY
