#!/usr/bin/env node
// magazine-watch.js — the optional local background transcription watcher for
// /magazine. Zero npm dependencies (node built-ins only). Requires: node >= 18.
//
// What it does: installs an OS-native scheduled job (launchd on macOS; systemd
// user timer, cron fallback, on Linux) that wakes every N hours and runs
// `magazine-run.js enqueue` then `drain`, keeping the transcription queue warm so
// interactive issue creation is mostly cache hits. Opt-in and fully reversible.
//
// Subcommands (dispatched from /magazine watch ...):
//   install [--interval H] [--max K] [--ac-only] [--backfill DAYS]
//   status | run-now | uninstall
//
// CLI:  node magazine-watch.js <install|status|run-now|uninstall|--selftest> [opts]
'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');
const state = require('./magazine-state.js');
const run = require('./magazine-run.js');

const LABEL = 'com.pmos.magazine.watch';        // launchd label
const UNIT = 'pmos-magazine-watch';             // systemd unit / cron tag
const CRON_TAG = '# pmos-magazine-watch';

function defaultRoot() { return path.join(os.homedir(), '.pmos', 'magazine'); }
function logPathOf(root) { return path.join(root, 'watch.log'); }
function wrapperPathOf(root) { return path.join(root, 'watch-run.sh'); }
function plistPathOf() { return path.join(os.homedir(), 'Library', 'LaunchAgents', LABEL + '.plist'); }
function systemdDir() { return path.join(os.homedir(), '.config', 'systemd', 'user'); }
function servicePathOf() { return path.join(systemdDir(), UNIT + '.service'); }
function timerPathOf() { return path.join(systemdDir(), UNIT + '.timer'); }

// --- Pure generators (snapshot-tested) ---

// The wrapper the scheduler runs: enqueue then drain, logging to watch.log. When
// acOnly, it self-skips on battery (portable across launchd/systemd/cron — the
// scheduler artifacts have no uniform AC condition).
function wrapperFor(opts) {
  const node = opts.nodePath;
  const runJs = path.join(opts.scriptsDir, 'magazine-run.js');
  const log = opts.logPath;
  const max = opts.max || 5;
  const acGuard = opts.acOnly
    ? '# --ac-only: skip while on battery\n' +
      'if command -v pmset >/dev/null 2>&1; then\n' +
      '  pmset -g ps | grep -q "AC Power" || { echo "$(date): skip (on battery)" >> "' + log + '"; exit 0; }\n' +
      'elif ls /sys/class/power_supply/A*/online >/dev/null 2>&1; then\n' +
      '  [ "$(cat /sys/class/power_supply/A*/online 2>/dev/null | head -1)" = "1" ] || { echo "$(date): skip (on battery)" >> "' + log + '"; exit 0; }\n' +
      'fi\n'
    : '';
  return '#!/bin/sh\n' +
    '# pmos-magazine-watch — generated by /magazine watch --install. Edit via re-install.\n' +
    acGuard +
    'echo "$(date): tick" >> "' + log + '"\n' +
    '"' + node + '" "' + runJs + '" enqueue >> "' + log + '" 2>&1\n' +
    '"' + node + '" "' + runJs + '" drain --max ' + max + ' >> "' + log + '" 2>&1\n';
}

function plistFor(opts) {
  const intervalSec = Math.max(60, Math.round((opts.intervalHours || 6) * 3600));
  return '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n' +
    '<plist version="1.0">\n<dict>\n' +
    '  <key>Label</key><string>' + LABEL + '</string>\n' +
    '  <key>ProgramArguments</key>\n  <array>\n' +
    '    <string>/bin/sh</string>\n    <string>' + opts.wrapperPath + '</string>\n  </array>\n' +
    '  <key>StartInterval</key><integer>' + intervalSec + '</integer>\n' +
    '  <key>ProcessType</key><string>Background</string>\n' +
    '  <key>Nice</key><integer>10</integer>\n' +
    '  <key>LowPriorityIO</key><true/>\n' +
    '  <key>RunAtLoad</key><false/>\n' +
    '  <key>StandardOutPath</key><string>' + opts.logPath + '</string>\n' +
    '  <key>StandardErrorPath</key><string>' + opts.logPath + '</string>\n' +
    '</dict>\n</plist>\n';
}

function systemdServiceFor(opts) {
  return '[Unit]\n' +
    'Description=pmos /magazine background transcription worker\n\n' +
    '[Service]\n' +
    'Type=oneshot\n' +
    'Nice=10\n' +
    'IOSchedulingClass=idle\n' +
    'ExecStart=/bin/sh ' + opts.wrapperPath + '\n';
}

function systemdTimerFor(opts) {
  const h = Math.max(1, Math.round(opts.intervalHours || 6));
  return '[Unit]\n' +
    'Description=pmos /magazine transcription timer\n\n' +
    '[Timer]\n' +
    'OnBootSec=5min\n' +
    'OnUnitActiveSec=' + h + 'h\n' +
    'Persistent=true\n\n' +
    '[Install]\n' +
    'WantedBy=timers.target\n';
}

function cronLineFor(opts) {
  const h = Math.max(1, Math.round(opts.intervalHours || 6));
  return '0 */' + h + ' * * * /bin/sh ' + opts.wrapperPath + ' ' + CRON_TAG + '\n';
}

// --- Precondition + plan (pure; testable) ---

// Returns {ok:true, ...} or {ok:false, reason, message}. Does NOT touch the OS.
function planInstall(opts) {
  if (!opts.whisperBin) {
    return { ok: false, reason: 'no-whisper',
      message: 'whisper not found — install openai-whisper (pip install openai-whisper) or whisper.cpp (brew install whisper-cpp), then re-run /magazine watch --install.' };
  }
  if (!opts.podcastCount || opts.podcastCount < 1) {
    return { ok: false, reason: 'no-podcast-feeds',
      message: 'no podcast feeds subscribed — add one with /magazine add <url> --type podcast (or /magazine add --bundle <id> --medium podcast), then re-run.' };
  }
  return { ok: true, platform: opts.platform, intervalHours: opts.intervalHours || 6, max: opts.max || 5 };
}

function detectWhisper(skillDir) {
  const t = path.join(skillDir, 'scripts', 'transcribe.sh');
  try { return execFileSync('bash', [t, '--detect']).toString().trim() || 'whisper'; }
  catch (_e) { return null; }
}

function podcastFeedCount(root) {
  try { return run.readFeedsTyped(root).filter((f) => f.type === 'podcast').length; }
  catch (_e) { return 0; }
}

// --- Side-effecting commands ---

function install(opts) {
  const root = opts.root || defaultRoot();
  const skillDir = opts.skillDir || path.join(__dirname, '..');
  const platform = opts.platform || process.platform;
  const whisperBin = opts.whisperBin !== undefined ? opts.whisperBin : detectWhisper(skillDir);
  const podcastCount = opts.podcastCount !== undefined ? opts.podcastCount : podcastFeedCount(root);

  const plan = planInstall({ whisperBin, podcastCount, platform, intervalHours: opts.interval, max: opts.max });
  if (!plan.ok) { process.stderr.write('magazine watch: ' + plan.message + '\n'); return plan; }

  fs.mkdirSync(root, { recursive: true });
  const logPath = logPathOf(root);
  const wrapperPath = wrapperPathOf(root);
  const gen = {
    nodePath: process.execPath, scriptsDir: __dirname, logPath, wrapperPath,
    intervalHours: plan.intervalHours, max: plan.max, acOnly: !!opts.acOnly,
  };
  // Optional one-time backfill enqueue is left to the first tick / explicit run;
  // forward-only is the default (FR-13). --backfill is recorded in the wrapper-less
  // path: the installer runs an immediate backfilled enqueue when asked.
  fs.writeFileSync(wrapperPath, wrapperFor(gen));
  fs.chmodSync(wrapperPath, 0o755);

  if (platform === 'darwin') {
    const p = plistPathOf();
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, plistFor(gen));
    tryExec('launchctl', ['bootstrap', 'gui/' + process.getuid(), p]) || tryExec('launchctl', ['load', p]);
    process.stdout.write('Installed launchd job ' + LABEL + ' — runs every ' + plan.intervalHours + 'h.\n');
  } else if (platform === 'linux') {
    if (hasSystemdUser()) {
      fs.mkdirSync(systemdDir(), { recursive: true });
      fs.writeFileSync(servicePathOf(), systemdServiceFor(gen));
      fs.writeFileSync(timerPathOf(), systemdTimerFor(gen));
      tryExec('systemctl', ['--user', 'daemon-reload']);
      tryExec('systemctl', ['--user', 'enable', '--now', UNIT + '.timer']);
      process.stdout.write('Installed systemd user timer ' + UNIT + '.timer — runs every ' + plan.intervalHours + 'h.\n');
    } else {
      installCron(gen);
      process.stdout.write('systemd --user unavailable; installed crontab entry (' + CRON_TAG + ') — runs every ' + plan.intervalHours + 'h.\n');
    }
  } else {
    process.stderr.write('magazine watch: unsupported platform "' + platform + '" (macOS + Linux only).\n');
    return { ok: false, reason: 'unsupported-platform' };
  }
  process.stdout.write('Log: ' + logPath + '   ·   Check: /magazine watch --status   ·   Remove: /magazine watch --uninstall\n');
  if (opts.backfill) {
    process.stdout.write('Backfilling the last ' + opts.backfill + ' day(s) into the queue...\n');
    run.cmdEnqueue({ root, backfill: opts.backfill });
  }
  return Object.assign({ ok: true, platform, wrapperPath }, plan);
}

function uninstall(opts) {
  const platform = (opts && opts.platform) || process.platform;
  const root = (opts && opts.root) || defaultRoot();
  let removed = 0;
  if (platform === 'darwin') {
    const p = plistPathOf();
    if (fs.existsSync(p)) {
      tryExec('launchctl', ['bootout', 'gui/' + process.getuid() + '/' + LABEL]) || tryExec('launchctl', ['unload', p]);
      fs.unlinkSync(p); removed++;
    }
  } else if (platform === 'linux') {
    if (fs.existsSync(timerPathOf()) || fs.existsSync(servicePathOf())) {
      tryExec('systemctl', ['--user', 'disable', '--now', UNIT + '.timer']);
      for (const f of [timerPathOf(), servicePathOf()]) if (fs.existsSync(f)) { fs.unlinkSync(f); removed++; }
      tryExec('systemctl', ['--user', 'daemon-reload']);
    }
    removed += removeCron();
  }
  const w = wrapperPathOf(root);
  if (fs.existsSync(w)) { fs.unlinkSync(w); }
  process.stdout.write(removed ? 'Uninstalled the magazine watcher. Cached transcripts kept.\n'
    : 'No magazine watcher installed — nothing to do.\n');
  return { ok: true, removed };
}

function status(opts) {
  const root = (opts && opts.root) || defaultRoot();
  const platform = (opts && opts.platform) || process.platform;
  const installed = platform === 'darwin' ? fs.existsSync(plistPathOf())
    : (fs.existsSync(timerPathOf()) || cronInstalled());
  const st = state.load(state.defaultPath ? path.join(root, 'state.json') : path.join(root, 'state.json'));
  const counts = Object.fromEntries(state.STATES.map((s) => [s, 0]));
  let claims = [];
  for (const guid of Object.keys(st.items || {})) {
    const it = st.items[guid];
    counts[it.status] = (counts[it.status] || 0) + 1;
    if (it.status === 'transcribing' && it.claim) claims.push({ guid, by: it.claim.by, at: it.claim.at });
  }
  const transcriptsDir = path.join(root, 'transcripts');
  const warm = fs.existsSync(transcriptsDir) ? fs.readdirSync(transcriptsDir).filter((f) => f.endsWith('.txt')).length : 0;
  const log = logPathOf(root);
  let lastLog = null;
  if (fs.existsSync(log)) {
    const lines = fs.readFileSync(log, 'utf8').trim().split('\n');
    lastLog = lines.slice(-3).join('\n');
  }
  const report = {
    installed, platform, warmTranscripts: warm,
    queue: { discovered: counts.discovered || 0, transcribing: counts.transcribing || 0, transcribed: counts.transcribed || 0, failed: counts.failed || 0 },
    inFlightClaims: claims, lastLog,
  };
  return report;
}

function runNow(opts) {
  const root = (opts && opts.root) || defaultRoot();
  const platform = (opts && opts.platform) || process.platform;
  if (platform === 'darwin' && fs.existsSync(plistPathOf())) {
    tryExec('launchctl', ['kickstart', '-k', 'gui/' + process.getuid() + '/' + LABEL]);
  } else if (platform === 'linux' && fs.existsSync(servicePathOf())) {
    tryExec('systemctl', ['--user', 'start', UNIT + '.service']);
  } else {
    // No scheduler (or cron fallback) — run the wrapper directly.
    const w = wrapperPathOf(root);
    if (fs.existsSync(w)) tryExec('/bin/sh', [w]);
    else { run.cmdEnqueue({ root }); run.cmdDrain({ root }); }
  }
  process.stdout.write('Triggered one transcription pass. Watch: ' + logPathOf(root) + '\n');
  return { ok: true };
}

// --- helpers ---
function tryExec(cmd, args) {
  try { execFileSync(cmd, args, { stdio: 'ignore' }); return true; } catch (_e) { return false; }
}
function hasSystemdUser() {
  try { execFileSync('systemctl', ['--user', '--version'], { stdio: 'ignore' }); return true; } catch (_e) { return false; }
}
function readCrontab() { try { return execFileSync('crontab', ['-l'], { stdio: ['ignore', 'pipe', 'ignore'] }).toString(); } catch (_e) { return ''; } }
function cronInstalled() { return readCrontab().includes(CRON_TAG); }
function installCron(gen) {
  const cur = readCrontab().split('\n').filter((l) => !l.includes(CRON_TAG)).join('\n').replace(/\n+$/, '\n');
  const next = (cur === '\n' || cur === '' ? '' : cur) + cronLineFor(gen);
  try { execFileSync('crontab', ['-'], { input: next }); } catch (_e) { /* surfaced by caller via no-tag */ }
}
function removeCron() {
  if (!cronInstalled()) return 0;
  const next = readCrontab().split('\n').filter((l) => !l.includes(CRON_TAG)).join('\n').replace(/\n+$/, '\n');
  try { execFileSync('crontab', ['-'], { input: next }); return 1; } catch (_e) { return 0; }
}

function selftest() {
  let ok = true;
  const assert = (c, m) => { if (!c) { ok = false; console.error('FAIL:', m); } };
  const gen = { nodePath: '/usr/bin/node', scriptsDir: '/skill/scripts', logPath: '/root/watch.log', wrapperPath: '/root/watch-run.sh', intervalHours: 6, max: 5, acOnly: false };

  // generators contain the expected knobs
  const plist = plistFor(gen);
  assert(plist.includes('<integer>21600</integer>'), 'plist StartInterval = 6h');
  assert(plist.includes('ProcessType') && plist.includes('Background'), 'plist ProcessType Background');
  assert(plist.includes('<key>LowPriorityIO</key><true/>'), 'plist LowPriorityIO');
  assert(plist.includes(LABEL), 'plist carries the label');

  const svc = systemdServiceFor(gen);
  assert(svc.includes('Type=oneshot') && svc.includes('IOSchedulingClass=idle'), 'systemd service oneshot + idle IO');
  const timer = systemdTimerFor(gen);
  assert(timer.includes('OnUnitActiveSec=6h') && timer.includes('Persistent=true'), 'systemd timer 6h + persistent');

  const cron = cronLineFor(gen);
  assert(cron.includes('0 */6 * * *') && cron.includes(CRON_TAG), 'cron line 6h + tag');

  const wrap = wrapperFor(gen);
  assert(wrap.includes('enqueue') && wrap.includes('drain --max 5'), 'wrapper runs enqueue then drain --max');
  const wrapAc = wrapperFor(Object.assign({}, gen, { acOnly: true }));
  assert(wrapAc.includes('on battery'), '--ac-only adds a battery guard to the wrapper');

  // planInstall refusals
  assert(planInstall({ whisperBin: null, podcastCount: 3 }).reason === 'no-whisper', 'refuse install with no whisper');
  assert(planInstall({ whisperBin: 'whisper', podcastCount: 0 }).reason === 'no-podcast-feeds', 'refuse install with no podcast feeds');
  assert(planInstall({ whisperBin: 'whisper', podcastCount: 1, platform: 'linux' }).ok === true, 'plan ok with whisper + a podcast feed');

  // uninstall when absent is a clean no-op
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'mag-watch-'));
  const u = uninstall({ platform: 'linux', root: tmp });
  assert(u.ok && u.removed === 0, 'uninstall when absent is a clean no-op');

  // status on an empty root reports not-installed + zeroed queue
  const rep = status({ platform: 'linux', root: tmp });
  assert(rep.installed === false && rep.warmTranscripts === 0 && rep.queue.discovered === 0, 'status on empty root is not-installed/empty');

  fs.rmSync(tmp, { recursive: true, force: true });
  console.log(ok ? 'magazine-watch.js --selftest: PASS' : 'magazine-watch.js --selftest: FAIL');
  process.exit(ok ? 0 : 1);
}

module.exports = {
  wrapperFor, plistFor, systemdServiceFor, systemdTimerFor, cronLineFor,
  planInstall, install, uninstall, status, runNow,
};

if (require.main === module) {
  const argv = process.argv.slice(2);
  if (argv.includes('--selftest')) { selftest(); }
  else {
    const cmd = argv[0];
    const o = { interval: 0, max: 0, acOnly: false, backfill: 0 };
    for (let i = 1; i < argv.length; i++) {
      const a = argv[i];
      if (a === '--interval') o.interval = parseInt(argv[++i], 10) || 0;
      else if (a === '--max') o.max = parseInt(argv[++i], 10) || 0;
      else if (a === '--ac-only') o.acOnly = true;
      else if (a === '--backfill') o.backfill = parseInt(argv[++i], 10) || 0;
    }
    if (cmd === 'install') install(o);
    else if (cmd === 'uninstall') uninstall(o);
    else if (cmd === 'status') process.stdout.write(JSON.stringify(status(o), null, 2) + '\n');
    else if (cmd === 'run-now') runNow(o);
    else { process.stderr.write('usage: magazine-watch.js <install|status|run-now|uninstall> [opts] | --selftest\n'); process.exit(64); }
  }
}
