#!/usr/bin/env node
// magazine-watch.js — the optional local background transcription watcher for
// /magazine. Zero npm dependencies (node built-ins only). Requires: node >= 18.
//
// What it does: installs an OS-native scheduled job (launchd on macOS; systemd
// user timer, cron fallback, on Linux) that wakes every N hours and runs
// `magazine-run.js enqueue` then `drain`, keeping the transcription queue warm so
// interactive issue creation is mostly cache hits. Opt-in and fully reversible.
//
// Subcommands (dispatched from /magazine watch ...):
//   install [--interval H] [--max K] [--ac-only] [--backfill DAYS]
//   status | run-now | uninstall
//
// CLI:  node magazine-watch.js <install|status|run-now|uninstall|--selftest> [opts]
'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');
const state = require('./magazine-state.js');
const run = require('./magazine-run.js');

const LABEL = 'com.pmos.magazine.watch';        // launchd label
const UNIT = 'pmos-magazine-watch';             // systemd unit / cron tag
const CRON_TAG = '# pmos-magazine-watch';

function defaultRoot() { return path.join(os.homedir(), '.pmos', 'magazine'); }
function logPathOf(root) { return path.join(root, 'watch.log'); }
function wrapperPathOf(root) { return path.join(root, 'watch-run.sh'); }
function plistPathOf() { return path.join(os.homedir(), 'Library', 'LaunchAgents', LABEL + '.plist'); }
function systemdDir() { return path.join(os.homedir(), '.config', 'systemd', 'user'); }
function servicePathOf() { return path.join(systemdDir(), UNIT + '.service'); }
function timerPathOf() { return path.join(systemdDir(), UNIT + '.timer'); }

// --- Pure generators (snapshot-tested) ---

// The PATH the scheduler-run wrapper/plist must carry (FR-R3). launchd + cron
// inherit only a minimal `/usr/bin:/bin:/usr/sbin:/sbin`, so Homebrew binaries
// (whisper-cli, ffmpeg in /opt/homebrew/bin) are unreachable — the worker would
// transcribe nothing, silently, forever. We prepend the detected whisper dir
// (which also holds ffmpeg) plus the common Homebrew/local prefixes.
function schedulerPath(whisperDir) {
  const dirs = [whisperDir, '/opt/homebrew/bin', '/usr/local/bin', '/usr/bin', '/bin', '/usr/sbin', '/sbin'];
  return dirs.filter(Boolean).join(':');
}

// The wrapper the scheduler runs: enqueue then drain, logging to watch.log. When
// acOnly, it self-skips on battery (portable across launchd/systemd/cron — the
// scheduler artifacts have no uniform AC condition).
function wrapperFor(opts) {
  const node = opts.nodePath;
  const runJs = path.join(opts.scriptsDir, 'magazine-run.js');
  const log = opts.logPath;
  const max = opts.max || 5;
  const rootArg = opts.root ? ' --root "' + opts.root + '"' : '';
  const pathLine = 'PATH="' + schedulerPath(opts.whisperDir) + '"\nexport PATH\n';
  const acGuard = opts.acOnly
    ? '# --ac-only: skip while on battery\n' +
      'if command -v pmset >/dev/null 2>&1; then\n' +
      '  pmset -g ps | grep -q "AC Power" || { echo "$(date): skip (on battery)" >> "' + log + '"; exit 0; }\n' +
      'elif ls /sys/class/power_supply/A*/online >/dev/null 2>&1; then\n' +
      '  [ "$(cat /sys/class/power_supply/A*/online 2>/dev/null | head -1)" = "1" ] || { echo "$(date): skip (on battery)" >> "' + log + '"; exit 0; }\n' +
      'fi\n'
    : '';
  return '#!/bin/sh\n' +
    '# pmos-magazine-watch — generated by /magazine watch --install. Edit via re-install.\n' +
    pathLine +
    acGuard +
    'echo "$(date): tick" >> "' + log + '"\n' +
    '"' + node + '" "' + runJs + '" enqueue' + rootArg + ' >> "' + log + '" 2>&1\n' +
    '"' + node + '" "' + runJs + '" drain --max ' + max + rootArg + ' >> "' + log + '" 2>&1\n';
}

function plistFor(opts) {
  const intervalSec = Math.max(60, Math.round((opts.intervalHours || 6) * 3600));
  return '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n' +
    '<plist version="1.0">\n<dict>\n' +
    '  <key>Label</key><string>' + LABEL + '</string>\n' +
    '  <key>ProgramArguments</key>\n  <array>\n' +
    '    <string>/bin/sh</string>\n    <string>' + opts.wrapperPath + '</string>\n  </array>\n' +
    '  <key>StartInterval</key><integer>' + intervalSec + '</integer>\n' +
    '  <key>ProcessType</key><string>Background</string>\n' +
    '  <key>Nice</key><integer>10</integer>\n' +
    '  <key>LowPriorityIO</key><true/>\n' +
    '  <key>RunAtLoad</key><false/>\n' +
    // launchd inherits a minimal PATH; carry the whisper/Homebrew dirs explicitly
    // so the scheduled job can find whisper-cli + ffmpeg (FR-R3).
    '  <key>EnvironmentVariables</key>\n  <dict>\n' +
    '    <key>PATH</key><string>' + schedulerPath(opts.whisperDir) + '</string>\n  </dict>\n' +
    '  <key>StandardOutPath</key><string>' + opts.logPath + '</string>\n' +
    '  <key>StandardErrorPath</key><string>' + opts.logPath + '</string>\n' +
    '</dict>\n</plist>\n';
}

function systemdServiceFor(opts) {
  return '[Unit]\n' +
    'Description=pmos /magazine background transcription worker\n\n' +
    '[Service]\n' +
    'Type=oneshot\n' +
    'Nice=10\n' +
    'IOSchedulingClass=idle\n' +
    'ExecStart=/bin/sh ' + opts.wrapperPath + '\n';
}

function systemdTimerFor(opts) {
  const h = Math.max(1, Math.round(opts.intervalHours || 6));
  return '[Unit]\n' +
    'Description=pmos /magazine transcription timer\n\n' +
    '[Timer]\n' +
    'OnBootSec=5min\n' +
    'OnUnitActiveSec=' + h + 'h\n' +
    'Persistent=true\n\n' +
    '[Install]\n' +
    'WantedBy=timers.target\n';
}

function cronLineFor(opts) {
  const h = Math.max(1, Math.round(opts.intervalHours || 6));
  return '0 */' + h + ' * * * /bin/sh ' + opts.wrapperPath + ' ' + CRON_TAG + '\n';
}

// --- Precondition + plan (pure; testable) ---

// Returns {ok:true, ...} or {ok:false, reason, message}. Does NOT touch the OS.
function planInstall(opts) {
  if (!opts.whisperBin) {
    return { ok: false, reason: 'no-whisper',
      message: 'whisper not found — install openai-whisper (pip install openai-whisper) or whisper.cpp (brew install whisper-cpp), then re-run /magazine watch --install.' };
  }
  if (!opts.podcastCount || opts.podcastCount < 1) {
    return { ok: false, reason: 'no-podcast-feeds',
      message: 'no podcast feeds subscribed — add one with /magazine add <url> --type podcast (or /magazine add --bundle <id> --medium podcast), then re-run.' };
  }
  return { ok: true, platform: opts.platform, intervalHours: opts.intervalHours || 6, max: opts.max || 5 };
}

function detectWhisper(skillDir) {
  const t = path.join(skillDir, 'scripts', 'transcribe.sh');
  try { return execFileSync('bash', [t, '--detect']).toString().trim() || 'whisper'; }
  catch (_e) { return null; }
}

// Resolve the directory of the detected whisper binary so it can be baked into
// the scheduler PATH (FR-R3). Runs under the install-time (interactive) PATH,
// which includes Homebrew, so `command -v` finds /opt/homebrew/bin/whisper-cli.
function whisperDir(bin) {
  if (!bin) return null;
  try {
    const p = execFileSync('bash', ['-c', 'command -v ' + bin], { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
    return p ? path.dirname(p) : null;
  } catch (_e) { return null; }
}

// The whisper model the scheduler will use: the first podcast feed's
// whisper_model, else `base`. Used by the install smoke check (FR-R6).
function defaultModel(root) {
  try {
    const pod = run.readFeedsTyped(root).find((f) => f.type === 'podcast');
    return (pod && pod.whisper_model) || 'base';
  } catch (_e) { return 'base'; }
}

function podcastFeedCount(root) {
  try { return run.readFeedsTyped(root).filter((f) => f.type === 'podcast').length; }
  catch (_e) { return 0; }
}

// Seed each podcast feed's cursor to NOW (forward-only default, FR-R4) — only
// where ABSENT, so an existing position from a prior interactive build is kept.
// Legacy URL-keyed cursors are unified to the slug first. Returns count seeded.
function seedForwardCursors(root) {
  const stFile = path.join(root, 'state.json');
  const st = state.load(stFile);
  state.remapCursors(st, run.feedKeyPairs(root));
  const now = new Date().toISOString();
  let seeded = 0;
  for (const f of run.readFeedsTyped(root).filter((x) => x.type === 'podcast')) {
    const key = f.name || f.url;
    if (st.cursors[key] === undefined) { st.cursors[key] = now; seeded++; }
  }
  state.save(stFile, st);
  return seeded;
}

// Run transcribe.sh --check-model under the SAME minimal env the scheduler uses
// (PATH from schedulerPath, no shell-set WHISPER_MODEL_DIR), so the install
// smoke check faithfully reproduces what launchd/cron will see (FR-R6). Returns
// { ok, message }. Never throws.
function smokeCheck(opts) {
  const t = path.join(opts.skillDir || path.join(__dirname, '..'), 'scripts', 'transcribe.sh');
  const env = { HOME: os.homedir(), PATH: schedulerPath(opts.whisperDir) };
  try {
    const out = execFileSync('bash', [t, '--check-model', opts.model || 'base'],
      { env, stdio: ['ignore', 'pipe', 'pipe'] }).toString().trim();
    return { ok: true, message: out || ('found-whisper: yes · model ' + (opts.model || 'base') + ': resolved') };
  } catch (e) {
    const err = ((e.stderr ? e.stderr.toString() : '') + (e.stdout ? e.stdout.toString() : '')).trim();
    return { ok: false, message: err || ('whisper/model check failed (exit ' + (e.status || 1) + ') for model ' + (opts.model || 'base')) };
  }
}

// --- Side-effecting commands ---

function install(opts) {
  const root = opts.root || defaultRoot();
  const skillDir = opts.skillDir || path.join(__dirname, '..');
  const platform = opts.platform || process.platform;
  const whisperBin = opts.whisperBin !== undefined ? opts.whisperBin : detectWhisper(skillDir);
  const podcastCount = opts.podcastCount !== undefined ? opts.podcastCount : podcastFeedCount(root);

  const plan = planInstall({ whisperBin, podcastCount, platform, intervalHours: opts.interval, max: opts.max });
  if (!plan.ok) { process.stderr.write('magazine watch: ' + plan.message + '\n'); return plan; }

  fs.mkdirSync(root, { recursive: true });
  const logPath = logPathOf(root);
  const wrapperPath = wrapperPathOf(root);
  const wdir = opts.whisperDir !== undefined ? opts.whisperDir : whisperDir(whisperBin);
  const gen = {
    nodePath: process.execPath, scriptsDir: __dirname, logPath, wrapperPath, root,
    intervalHours: plan.intervalHours, max: plan.max, acOnly: !!opts.acOnly, whisperDir: wdir,
  };
  // Forward-only is the default (FR-13); the scheduled wrapper always enqueues
  // forward. A --backfill at install time pulls history ONCE, via the immediate
  // enqueue at the end of this function (not baked into the recurring wrapper).
  fs.writeFileSync(wrapperPath, wrapperFor(gen));
  fs.chmodSync(wrapperPath, 0o755);

  if (platform === 'darwin') {
    const p = plistPathOf();
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, plistFor(gen));
    tryExec('launchctl', ['bootstrap', 'gui/' + process.getuid(), p]) || tryExec('launchctl', ['load', p]);
    process.stdout.write('Installed launchd job ' + LABEL + ' — runs every ' + plan.intervalHours + 'h.\n');
  } else if (platform === 'linux') {
    if (hasSystemdUser()) {
      fs.mkdirSync(systemdDir(), { recursive: true });
      fs.writeFileSync(servicePathOf(), systemdServiceFor(gen));
      fs.writeFileSync(timerPathOf(), systemdTimerFor(gen));
      tryExec('systemctl', ['--user', 'daemon-reload']);
      tryExec('systemctl', ['--user', 'enable', '--now', UNIT + '.timer']);
      process.stdout.write('Installed systemd user timer ' + UNIT + '.timer — runs every ' + plan.intervalHours + 'h.\n');
    } else {
      installCron(gen);
      process.stdout.write('systemd --user unavailable; installed crontab entry (' + CRON_TAG + ') — runs every ' + plan.intervalHours + 'h.\n');
    }
  } else {
    process.stderr.write('magazine watch: unsupported platform "' + platform + '" (macOS + Linux only).\n');
    return { ok: false, reason: 'unsupported-platform' };
  }
  process.stdout.write('Log: ' + logPath + '   ·   Check: /magazine watch --status   ·   Remove: /magazine watch --uninstall\n');

  // Forward-only is the default (FR-R4): seed each podcast feed's cursor to NOW so
  // the first scheduled enqueue pulls only NEW episodes, not the entire back
  // catalogue. Seed only ABSENT cursors — an existing cursor is a real position
  // (from a prior interactive build) and is respected. A --backfill install
  // skips seeding and pulls history once via the immediate enqueue below.
  let seeded = 0;
  if (!opts.backfill) {
    seeded = seedForwardCursors(root);
    if (seeded) process.stdout.write('Forward-only: seeded ' + seeded + ' podcast cursor(s) to now (no back-catalogue pull).\n');
  } else {
    process.stdout.write('Backfilling the last ' + opts.backfill + ' day(s) into the queue...\n');
    run.cmdEnqueue({ root, backfill: opts.backfill });
  }

  // Smoke check (FR-R6): verify the worker can actually transcribe BEFORE declaring
  // success — run transcribe.sh --check-model under the SAME minimal PATH the
  // scheduler will use (no shell env help), so a missing PATH entry or unresolved
  // model is caught now, not discovered as "transcribed nothing, forever".
  const smoke = smokeCheck({ skillDir, whisperDir: wdir, model: defaultModel(root) });
  if (smoke.ok) {
    process.stdout.write('Verified: ' + smoke.message + '\n');
  } else {
    process.stderr.write('WARNING — the scheduled worker will NOT transcribe yet: ' + smoke.message + '\n' +
      '  Fix: ensure whisper is on the scheduler PATH and the model resolves (drop ggml-<name>.bin in ~/.pmos/magazine/models/), then re-run /magazine watch --install.\n');
  }

  return Object.assign({ ok: true, platform, wrapperPath, whisperDir: wdir, seeded, smoke }, plan);
}

function uninstall(opts) {
  const platform = (opts && opts.platform) || process.platform;
  const root = (opts && opts.root) || defaultRoot();
  let removed = 0;
  if (platform === 'darwin') {
    const p = plistPathOf();
    if (fs.existsSync(p)) {
      tryExec('launchctl', ['bootout', 'gui/' + process.getuid() + '/' + LABEL]) || tryExec('launchctl', ['unload', p]);
      fs.unlinkSync(p); removed++;
    }
  } else if (platform === 'linux') {
    if (fs.existsSync(timerPathOf()) || fs.existsSync(servicePathOf())) {
      tryExec('systemctl', ['--user', 'disable', '--now', UNIT + '.timer']);
      for (const f of [timerPathOf(), servicePathOf()]) if (fs.existsSync(f)) { fs.unlinkSync(f); removed++; }
      tryExec('systemctl', ['--user', 'daemon-reload']);
    }
    removed += removeCron();
  }
  const w = wrapperPathOf(root);
  if (fs.existsSync(w)) { fs.unlinkSync(w); }
  process.stdout.write(removed ? 'Uninstalled the magazine watcher. Cached transcripts kept.\n'
    : 'No magazine watcher installed — nothing to do.\n');
  return { ok: true, removed };
}

function status(opts) {
  const root = (opts && opts.root) || defaultRoot();
  const platform = (opts && opts.platform) || process.platform;
  const installed = platform === 'darwin' ? fs.existsSync(plistPathOf())
    : (fs.existsSync(timerPathOf()) || cronInstalled());
  const st = state.load(path.join(root, 'state.json'));
  const counts = Object.fromEntries(state.STATES.map((s) => [s, 0]));
  let claims = [];
  for (const guid of Object.keys(st.items || {})) {
    const it = st.items[guid];
    counts[it.status] = (counts[it.status] || 0) + 1;
    if (it.status === 'transcribing' && it.claim) claims.push({ guid, by: it.claim.by, at: it.claim.at });
  }
  const transcriptsDir = path.join(root, 'transcripts');
  const warm = fs.existsSync(transcriptsDir) ? fs.readdirSync(transcriptsDir).filter((f) => f.endsWith('.txt')).length : 0;
  const log = logPathOf(root);
  let lastLog = null;
  if (fs.existsSync(log)) {
    const lines = fs.readFileSync(log, 'utf8').trim().split('\n');
    lastLog = lines.slice(-3).join('\n');
  }
  const report = {
    installed, platform, warmTranscripts: warm,
    queue: { discovered: counts.discovered || 0, transcribing: counts.transcribing || 0, transcribed: counts.transcribed || 0, failed: counts.failed || 0 },
    inFlightClaims: claims, lastLog,
  };
  return report;
}

function runNow(opts) {
  const root = (opts && opts.root) || defaultRoot();
  const platform = (opts && opts.platform) || process.platform;
  if (platform === 'darwin' && fs.existsSync(plistPathOf())) {
    tryExec('launchctl', ['kickstart', '-k', 'gui/' + process.getuid() + '/' + LABEL]);
  } else if (platform === 'linux' && fs.existsSync(servicePathOf())) {
    tryExec('systemctl', ['--user', 'start', UNIT + '.service']);
  } else {
    // No scheduler (or cron fallback) — run the wrapper directly.
    const w = wrapperPathOf(root);
    if (fs.existsSync(w)) tryExec('/bin/sh', [w]);
    else { run.cmdEnqueue({ root }); run.cmdDrain({ root }); }
  }
  process.stdout.write('Triggered one transcription pass. Watch: ' + logPathOf(root) + '\n');
  return { ok: true };
}

// --- helpers ---
function tryExec(cmd, args) {
  try { execFileSync(cmd, args, { stdio: 'ignore' }); return true; } catch (_e) { return false; }
}
function hasSystemdUser() {
  try { execFileSync('systemctl', ['--user', '--version'], { stdio: 'ignore' }); return true; } catch (_e) { return false; }
}
function readCrontab() { try { return execFileSync('crontab', ['-l'], { stdio: ['ignore', 'pipe', 'ignore'] }).toString(); } catch (_e) { return ''; } }
function cronInstalled() { return readCrontab().includes(CRON_TAG); }
function installCron(gen) {
  const cur = readCrontab().split('\n').filter((l) => !l.includes(CRON_TAG)).join('\n').replace(/\n+$/, '\n');
  const next = (cur === '\n' || cur === '' ? '' : cur) + cronLineFor(gen);
  try { execFileSync('crontab', ['-'], { input: next }); } catch (_e) { /* surfaced by caller via no-tag */ }
}
function removeCron() {
  if (!cronInstalled()) return 0;
  const next = readCrontab().split('\n').filter((l) => !l.includes(CRON_TAG)).join('\n').replace(/\n+$/, '\n');
  try { execFileSync('crontab', ['-'], { input: next }); return 1; } catch (_e) { return 0; }
}

function selftest() {
  let ok = true;
  const assert = (c, m) => { if (!c) { ok = false; console.error('FAIL:', m); } };
  const gen = { nodePath: '/usr/bin/node', scriptsDir: '/skill/scripts', logPath: '/root/watch.log', wrapperPath: '/root/watch-run.sh', intervalHours: 6, max: 5, acOnly: false };

  // generators contain the expected knobs
  const plist = plistFor(gen);
  assert(plist.includes('<integer>21600</integer>'), 'plist StartInterval = 6h');
  assert(plist.includes('ProcessType') && plist.includes('Background'), 'plist ProcessType Background');
  assert(plist.includes('<key>LowPriorityIO</key><true/>'), 'plist LowPriorityIO');
  assert(plist.includes(LABEL), 'plist carries the label');

  const svc = systemdServiceFor(gen);
  assert(svc.includes('Type=oneshot') && svc.includes('IOSchedulingClass=idle'), 'systemd service oneshot + idle IO');
  const timer = systemdTimerFor(gen);
  assert(timer.includes('OnUnitActiveSec=6h') && timer.includes('Persistent=true'), 'systemd timer 6h + persistent');

  const cron = cronLineFor(gen);
  assert(cron.includes('0 */6 * * *') && cron.includes(CRON_TAG), 'cron line 6h + tag');

  const wrap = wrapperFor(gen);
  assert(wrap.includes('enqueue') && wrap.includes('drain --max 5'), 'wrapper runs enqueue then drain --max');
  const wrapAc = wrapperFor(Object.assign({}, gen, { acOnly: true }));
  assert(wrapAc.includes('on battery'), '--ac-only adds a battery guard to the wrapper');
  const wrapRoot = wrapperFor(Object.assign({}, gen, { root: '/r' }));
  assert(wrapRoot.includes('enqueue --root "/r"') && wrapRoot.includes('--root "/r" >>'), 'wrapper targets the installed root via --root');

  // FR-R3: wrapper + plist carry a PATH that includes the detected whisper dir,
  // so the scheduler (minimal PATH) can reach whisper-cli/ffmpeg.
  const wrapW = wrapperFor(Object.assign({}, gen, { whisperDir: '/opt/homebrew/bin' }));
  assert(/\nPATH="[^"]+"\nexport PATH\n/.test(wrapW), 'FR-R3: wrapper exports a PATH line');
  assert(wrapW.includes('/opt/homebrew/bin'), 'FR-R3: wrapper PATH includes the whisper dir');
  const plistW = plistFor(Object.assign({}, gen, { whisperDir: '/opt/homebrew/bin' }));
  assert(plistW.includes('<key>EnvironmentVariables</key>') && plistW.includes('<key>PATH</key>'),
    'FR-R3: plist sets EnvironmentVariables > PATH');
  assert(plistW.includes('/opt/homebrew/bin'), 'FR-R3: plist PATH includes the whisper dir');
  // schedulerPath is robust to a null whisperDir (no empty leading segment).
  assert(schedulerPath(null).includes('/usr/bin') && !schedulerPath(null).startsWith(':'),
    'schedulerPath tolerates a null whisper dir');

  // FR-R4: install seeds forward-only cursors (absent-only) for podcast feeds.
  const sroot = fs.mkdtempSync(path.join(os.tmpdir(), 'mag-seed-'));
  fs.writeFileSync(path.join(sroot, 'feeds.yaml'),
    'feeds:\n  - name: pod1\n    url: http://x/p1\n    type: podcast\n  - name: news1\n    url: http://x/n1\n    type: newsletter\n');
  const n1 = seedForwardCursors(sroot);
  assert(n1 === 1, 'FR-R4: seedForwardCursors seeds exactly the podcast feed (got ' + n1 + ')');
  const sst = state.load(path.join(sroot, 'state.json'));
  assert(typeof sst.cursors.pod1 === 'string' && sst.cursors.news1 === undefined, 'FR-R4: only the podcast cursor is seeded');
  const n2 = seedForwardCursors(sroot);
  assert(n2 === 0, 'FR-R4: re-seed is a no-op (existing cursor respected)');
  fs.rmSync(sroot, { recursive: true, force: true });

  // FR-R6: smokeCheck returns a structured {ok, message} and never throws.
  const sc = smokeCheck({ skillDir: path.join(__dirname, '..'), whisperDir: null, model: 'base' });
  assert(typeof sc.ok === 'boolean' && typeof sc.message === 'string', 'FR-R6: smokeCheck returns {ok, message}');

  // planInstall refusals
  assert(planInstall({ whisperBin: null, podcastCount: 3 }).reason === 'no-whisper', 'refuse install with no whisper');
  assert(planInstall({ whisperBin: 'whisper', podcastCount: 0 }).reason === 'no-podcast-feeds', 'refuse install with no podcast feeds');
  assert(planInstall({ whisperBin: 'whisper', podcastCount: 1, platform: 'linux' }).ok === true, 'plan ok with whisper + a podcast feed');

  // uninstall when absent is a clean no-op
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'mag-watch-'));
  const u = uninstall({ platform: 'linux', root: tmp });
  assert(u.ok && u.removed === 0, 'uninstall when absent is a clean no-op');

  // status on an empty root reports not-installed + zeroed queue
  const rep = status({ platform: 'linux', root: tmp });
  assert(rep.installed === false && rep.warmTranscripts === 0 && rep.queue.discovered === 0, 'status on empty root is not-installed/empty');

  fs.rmSync(tmp, { recursive: true, force: true });
  console.log(ok ? 'magazine-watch.js --selftest: PASS' : 'magazine-watch.js --selftest: FAIL');
  process.exit(ok ? 0 : 1);
}

module.exports = {
  wrapperFor, plistFor, systemdServiceFor, systemdTimerFor, cronLineFor, schedulerPath,
  planInstall, install, uninstall, status, runNow, whisperDir, smokeCheck, seedForwardCursors, defaultModel,
};

if (require.main === module) {
  const argv = process.argv.slice(2);
  if (argv.includes('--selftest')) { selftest(); }
  else {
    const cmd = argv[0];
    const o = { interval: 0, max: 0, acOnly: false, backfill: 0 };
    for (let i = 1; i < argv.length; i++) {
      const a = argv[i];
      if (a === '--interval') o.interval = parseInt(argv[++i], 10) || 0;
      else if (a === '--max') o.max = parseInt(argv[++i], 10) || 0;
      else if (a === '--ac-only') o.acOnly = true;
      else if (a === '--backfill') o.backfill = parseInt(argv[++i], 10) || 0;
      else if (a === '--root') o.root = argv[++i];
    }
    if (cmd === 'install') { const r = install(o); if (r && r.ok === false) process.exit(64); }
    else if (cmd === 'uninstall') uninstall(o);
    else if (cmd === 'status') process.stdout.write(JSON.stringify(status(o), null, 2) + '\n');
    else if (cmd === 'run-now') runNow(o);
    else { process.stderr.write('usage: magazine-watch.js <install|status|run-now|uninstall> [opts] | --selftest\n'); process.exit(64); }
  }
}
